using System;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection;
using AgileObjects.ReadableExpressions.Visualizers.NetCore;

[assembly: AssemblyDescription("A Debugger Visualizer providing readable string representations of Expressions, Types and MethodInfos for Visual Studio 16 .NET Core")]

[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Expression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(BinaryExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(BlockExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(ConditionalExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(ConstantExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(DebugInfoExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(DefaultExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(DynamicExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(GotoExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(IndexExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(InvocationExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(LabelExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(LambdaExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(ListInitExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(LoopExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(MemberExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(MemberInitExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(MethodCallExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(NewArrayExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(NewExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(ParameterExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(RuntimeVariablesExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(SwitchExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(TryExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(TypeBinaryExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(UnaryExpression), Description = "ReadableExpressions Visualizer (.NET Core)")]

[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Type), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(MethodBase), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(ConstructorInfo), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(MethodInfo), Description = "ReadableExpressions Visualizer (.NET Core)")]

[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Func<,,,,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]

[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]
[assembly: DebuggerVisualizer(typeof(Vs16NetCoreExpressionVisualizer), typeof(Vs16NetCoreExpressionVisualizerObjectSource), Target = typeof(Action<,,,,,,,,,,,,,,>), Description = "ReadableExpressions Visualizer (.NET Core)")]

